[2023-11-26T19:29:08.223+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.insert_province_daily manual__2023-11-26T19:29:04.554090+00:00 [queued]>
[2023-11-26T19:29:08.230+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.insert_province_daily manual__2023-11-26T19:29:04.554090+00:00 [queued]>
[2023-11-26T19:29:08.231+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T19:29:08.242+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_province_daily> on 2023-11-26 19:29:04.554090+00:00
[2023-11-26T19:29:08.248+0000] {standard_task_runner.py:57} INFO - Started process 2212 to run task
[2023-11-26T19:29:08.252+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_finalpro_fredicia', 'insert_province_daily', 'manual__2023-11-26T19:29:04.554090+00:00', '--job-id', '341', '--raw', '--subdir', 'DAGS_FOLDER/dag-finalpro-fredicia.py', '--cfg-path', '/tmp/tmpj_7z52i_']
[2023-11-26T19:29:08.254+0000] {standard_task_runner.py:85} INFO - Job 341: Subtask insert_province_daily
[2023-11-26T19:29:08.289+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_finalpro_fredicia.insert_province_daily manual__2023-11-26T19:29:04.554090+00:00 [running]> on host 316a5e988948
[2023-11-26T19:29:08.350+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_finalpro_fredicia' AIRFLOW_CTX_TASK_ID='insert_province_daily' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T19:29:04.554090+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T19:29:04.554090+00:00'
[2023-11-26T19:29:08.366+0000] {logging_mixin.py:151} INFO - Connecting to MySQL
[2023-11-26T19:29:08.366+0000] {logging_mixin.py:151} INFO - ***+***connector://***:***@172.17.0.1:3307/***
[2023-11-26T19:29:08.627+0000] {logging_mixin.py:151} INFO - Connecting to MySQL
[2023-11-26T19:29:08.627+0000] {logging_mixin.py:151} INFO - ***+***connector://***:***@172.17.0.1:5435/dwh
[2023-11-26T19:29:08.628+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-finalpro-fredicia.py", line 58, in func_insert_province_daily
    generator_province.create_province_daily()
  File "/opt/airflow/dags/modules/transformer.py", line 75, in create_province_daily
    df = self.get_data_from_mysql()
TypeError: get_data_from_***() missing 2 required positional arguments: 'engine_sql' and 'engine_***'
[2023-11-26T19:29:08.634+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_finalpro_fredicia, task_id=insert_province_daily, execution_date=20231126T192904, start_date=20231126T192908, end_date=20231126T192908
[2023-11-26T19:29:08.645+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 341 for task insert_province_daily (get_data_from_***() missing 2 required positional arguments: 'engine_sql' and 'engine_***'; 2212)
[2023-11-26T19:29:08.669+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T19:29:08.682+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
