[2023-11-26T19:33:05.016+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.insert_province_daily manual__2023-11-26T19:33:01.963623+00:00 [queued]>
[2023-11-26T19:33:05.024+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.insert_province_daily manual__2023-11-26T19:33:01.963623+00:00 [queued]>
[2023-11-26T19:33:05.024+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T19:33:05.035+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_province_daily> on 2023-11-26 19:33:01.963623+00:00
[2023-11-26T19:33:05.040+0000] {standard_task_runner.py:57} INFO - Started process 2308 to run task
[2023-11-26T19:33:05.044+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_finalpro_fredicia', 'insert_province_daily', 'manual__2023-11-26T19:33:01.963623+00:00', '--job-id', '349', '--raw', '--subdir', 'DAGS_FOLDER/dag-finalpro-fredicia.py', '--cfg-path', '/tmp/tmp0gqqze_5']
[2023-11-26T19:33:05.045+0000] {standard_task_runner.py:85} INFO - Job 349: Subtask insert_province_daily
[2023-11-26T19:33:05.078+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_finalpro_fredicia.insert_province_daily manual__2023-11-26T19:33:01.963623+00:00 [running]> on host 316a5e988948
[2023-11-26T19:33:05.135+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_finalpro_fredicia' AIRFLOW_CTX_TASK_ID='insert_province_daily' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T19:33:01.963623+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T19:33:01.963623+00:00'
[2023-11-26T19:33:05.151+0000] {logging_mixin.py:151} INFO - Connecting to MySQL
[2023-11-26T19:33:05.152+0000] {logging_mixin.py:151} INFO - ***+***connector://***:***@172.17.0.1:3307/***
[2023-11-26T19:33:05.407+0000] {logging_mixin.py:151} INFO - Connecting to PostgreSQL
[2023-11-26T19:33:05.408+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-finalpro-fredicia.py", line 58, in func_insert_province_daily
    generator_province.create_province_daily()
  File "/opt/airflow/dags/modules/transformer.py", line 75, in create_province_daily
    df = self.get_data_from_mysql()
TypeError: get_data_from_***() missing 2 required positional arguments: 'engine_sql' and 'engine_***'
[2023-11-26T19:33:05.414+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_finalpro_fredicia, task_id=insert_province_daily, execution_date=20231126T193301, start_date=20231126T193305, end_date=20231126T193305
[2023-11-26T19:33:05.431+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 349 for task insert_province_daily (get_data_from_***() missing 2 required positional arguments: 'engine_sql' and 'engine_***'; 2308)
[2023-11-26T19:33:05.459+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T19:33:05.473+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
