[2023-11-26T19:45:03.785+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T19:45:02.135068+00:00 [queued]>
[2023-11-26T19:45:03.793+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T19:45:02.135068+00:00 [queued]>
[2023-11-26T19:45:03.793+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T19:45:03.804+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): generate_dim> on 2023-11-26 19:45:02.135068+00:00
[2023-11-26T19:45:03.809+0000] {standard_task_runner.py:57} INFO - Started process 2485 to run task
[2023-11-26T19:45:03.811+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_finalpro_fredicia', 'generate_dim', 'manual__2023-11-26T19:45:02.135068+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/dag-finalpro-fredicia.py', '--cfg-path', '/tmp/tmpzf24flgz']
[2023-11-26T19:45:03.812+0000] {standard_task_runner.py:85} INFO - Job 356: Subtask generate_dim
[2023-11-26T19:45:03.844+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T19:45:02.135068+00:00 [running]> on host 316a5e988948
[2023-11-26T19:45:03.901+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_finalpro_fredicia' AIRFLOW_CTX_TASK_ID='generate_dim' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T19:45:02.135068+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T19:45:02.135068+00:00'
[2023-11-26T19:45:03.917+0000] {logging_mixin.py:151} INFO - Connecting to MySQL
[2023-11-26T19:45:03.917+0000] {logging_mixin.py:151} INFO - ***+***connector://***:***@172.17.0.1:3307/***
[2023-11-26T19:45:04.154+0000] {logging_mixin.py:151} INFO - Connecting to PostgreSQL
[2023-11-26T19:45:04.197+0000] {logging_mixin.py:151} INFO - GET DATA FROM MYSQL SUCCESS
[2023-11-26T19:45:04.220+0000] {logging_mixin.py:151} INFO - INSERTED dim_district TO POSTGRES SUCCESSFULLY
[2023-11-26T19:45:04.231+0000] {logging_mixin.py:151} INFO - GET DATA FROM MYSQL SUCCESS
[2023-11-26T19:45:04.242+0000] {logging_mixin.py:151} INFO - INSERTED dim_province TO POSTGRES SUCCESSFULLY
[2023-11-26T19:45:04.242+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-finalpro-fredicia.py", line 46, in func_generate_dim
    generator_dim.create_dimension_case()
  File "/opt/airflow/dags/modules/transformer.py", line 68, in create_dimension_case
    df = self.dataframe_dimension_case(self.engine_sql,self.engine_postgres)
TypeError: dataframe_dimension_case() takes 1 positional argument but 3 were given
[2023-11-26T19:45:04.248+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_finalpro_fredicia, task_id=generate_dim, execution_date=20231126T194502, start_date=20231126T194503, end_date=20231126T194504
[2023-11-26T19:45:04.258+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 356 for task generate_dim (dataframe_dimension_case() takes 1 positional argument but 3 were given; 2485)
[2023-11-26T19:45:04.272+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T19:45:04.291+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
